#   Copyright (C) 2023-2024 Credit Mutuel Arkea
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
"""Module for RAG Models"""

from enum import Enum, unique
from typing import List, Optional

from pydantic import AnyUrl, BaseModel, Field, HttpUrl

from gen_ai_orchestrator.models.vector_stores.vector_store_types import DocumentSearchParams


class Source(BaseModel):
    """A source model, used to associate document sources with the QA response"""

    title: str = Field(description='Source title', examples=['Tock Documentation'])
    url: Optional[AnyUrl] = Field(description='Source url', examples=['https://doc.tock.ai/tock/'], default=None)
    content: str = Field(description='Source content', examples=['Tock: The Open Conversation Kit'])
    score: Optional[float] = Field(description='The compressor score', examples=[0.9149009585380554], default=None)

    def __eq__(self, other):
        """
        Source are identified by their title and URL.
        When the identifier or the content are not the same for identical sources,
        this means that the sources are parts of the same document.
        """
        return (
            isinstance(other, Source)
            and self.title == other.title
            and self.url == other.url
            and self.content == other.content
        )

    def __hash__(self):
        return hash((self.title, str(self.url or ''), self.content))


class Footnote(Source):
    """A footnote model, used to associate document sources with the RAG answer"""

    identifier: str = Field(description='Footnote identifier', examples=['1'])

class ChunkInfos(BaseModel):
    """A model representing information about a chunk used in the RAG context."""

    chunk: Optional[str] = Field(
        description='Unique identifier of the chunk.',
        examples=['cd6d8221-ba9f-44da-86ee-0e25a3c9a5c7'],
        default=None
    )
    sentences: Optional[List[str]] = Field(
        description='List of verbatim sentences from the chunk that were used by the LLM.',
        default=None
    )
    reason: Optional[str] = Field(
        description='Reason why the chunk was not used (e.g., irrelevant, general background).',
        default=None
    )


class LLMAnswer(BaseModel):
    """
    A model representing the structured answer generated by the LLM
    in response to a user query, based on the provided RAG context.
    """

    status: Optional[str] = Field(
        description="The status of the answer generation. "
                    "Possible values: 'found_in_context', 'not_found_in_context', 'small_talk', "
                    "or other case-specific codes.",
        default=None
    )
    answer: Optional[str] = Field(
        description="The textual answer generated by the LLM, in the user's locale.",
        default=None
    )
    topic: Optional[str] = Field(
        description="The main topic assigned to the answer. Must be one of the predefined list "
                    "of topics, or 'unknown' if no match is possible.",
        default=None
    )
    suggested_topics: Optional[List[str]] = Field(
        description="A list of suggested alternative or related topics, "
                    "used when the main topic is 'unknown'.",
        default=None
    )
    context: Optional[List[ChunkInfos]] = Field(
        description="The list of chunks from the context that contributed to or were considered "
                    "in the LLM's answer. Each entry contains identifiers, sentences, and reasons.",
        default=None
    )

@unique
class ChatMessageType(str, Enum):
    """Enumeration to list a chat message type"""

    HUMAN = 'HUMAN'
    AI = 'AI'


class ChatMessage(BaseModel):
    """A conversation chat message"""

    text: str = Field(
        description='Conversation message text', examples=['Hello, how can I do this?']
    )
    type: ChatMessageType = Field(description='The message origin (Human or AI)')


class RAGDocumentMetadata(BaseModel):
    """The RAG document metadata"""

    index_session_id: str = Field(
        description='The indexing session id.', examples=['123f-ed01-gt21-gg08']
    )
    id: str = Field(description='The document id.', examples=['e014-g24-0f11-1g3e'])
    title: str = Field(description='The document title.', examples=['Tracking shot'])
    url: Optional[HttpUrl] = Field(
        description='The document url.',
        examples=['https://en.wikipedia.org/wiki/Tracking_shot'],
        default=None,
    )
    chunk: str = Field(description='The document chunk.', examples=['1/3'])
    retriever_score: Optional[float] = Field(
        description='The compressor score', examples=[0.9149009585380554], default=None
    )


class RAGDocument(BaseModel):
    """The definition of RAG document"""

    content: str = Field(
        description='The document content.',
        examples=[
            'In cinematography, a tracking shot is any shot where the camera follows backward, '
            'forward or moves alongside the subject being recorded.'
        ],
    )
    metadata: RAGDocumentMetadata = Field(
        description='The document metadata.',
    )


class QADebugData(BaseModel):
    """A QA debug data. This class is not currently used in the QA chain as Langfuse is now supported."""

    user_question: Optional[str] = Field(
        description="The user's initial question.",
        examples=["I'm interested in going to Morocco"],
    )
    documents: List[RAGDocument] = Field(
        description='Documents retrieved from the vector store.'
    )
    document_index_name: str = Field(
        description='Index name corresponding to a document collection in the vector database.',
    )
    document_search_params: DocumentSearchParams = Field(
        description='The document search parameters. Ex: number of documents, metadata filter',
    )
    duration: float = Field(
        description='The duration of RAG in seconds.', examples=['7.2']
    )


class RAGDebugData(QADebugData):
    """A RAG debug data"""

    question_condensing_prompt: Optional[str] = Field(
        description='The prompt of the question rephrased with the history of the conversation.',
        examples=['Given the following conversation, rephrase the follow up question to be a standalone question.'],
    )
    question_condensing_history: list[ChatMessage] = Field(
        description="Conversation history, used to reformulate the user's question.")
    condensed_question: Optional[str] = Field(
        description='The question rephrased with the history of the conversation.',
        examples=['Hello, how to plan a trip to Morocco ?'],
    )
    question_answering_prompt: Optional[str] = Field(
        description='The question answering prompt.',
        examples=[
            'Question: Hello, how to plan a trip to Morocco ?. Answer in French.'
        ],
    )
    answer: LLMAnswer = Field(description='The RAG answer.')
